version: "3.8"

services:
  backend:
    build: .
    container_name: backend_skilly_prod
    ports:
      - "0.0.0.0:5000:5000"
    restart: always
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
